#ifndef ZENIT_CONTEXT_H
#define ZENIT_CONTEXT_H

#include "ast/ast.h"
#include "symtable.h"
#include "source.h"

/*
 * Macro: zenit_context_error_count
 *  Returns the number of *errors* registered in the <struct ZenitContext> object
 *
 * Parameters:
 *  <struct ZenitContext> *ctxptr: A pointer to a <struct ZenitContext> object
 */
#define zenit_context_error_count(ctxptr) ((size_t)((ctxptr)->errors ? fl_list_length((ctxptr)->errors) : 0))


/*
 * Macro: zenit_context_has_errors
 *  Evaluates to *true* if the are *errors* registered in the <struct ZenitContext> object 
 *
 * Parameters:
 *  <struct ZenitContext> *ctxptr: A pointer to a <struct ZenitContext> object
 */
#define zenit_context_has_errors(ctxptr) ((ctxptr)->errors && fl_list_head((ctxptr)->errors) != NULL)

/*
 * Enum: enum ZenitErrorType 
 *  Represents every type of error that might occur in the
 *  compilation process
 *
 */
enum ZenitErrorType {
    // Zenit specific errors
    ZENIT_ERROR_INTERNAL,

    // Mostly missing/unexpected tokens
    ZENIT_ERROR_SYNTAX,

    // Number cannot be represented by any integer type
    ZENIT_ERROR_LARGE_INTEGER,

    // Symbol couldn't be found
    ZENIT_ERROR_MISSING_SYMBOL,

    // Symbol already exists
    ZENIT_ERROR_DUPLICATED_SYMBOL,

    // Cannot infer the type of an expression
    ZENIT_ERROR_INFERENCE,

    // An operation involves types that are incompatible
    ZENIT_ERROR_TYPE_MISSMATCH,

    // Error taking a reference from an expression
    ZENIT_ERROR_INVALID_REFERENCE,

    // A member of a compound type does not exist
    ZENIT_ERROR_UNKNOWN_MEMBER,

    // A member of a compound type is not initialized on type instance creation
    ZENIT_ERROR_UNINITIALIZED_MEMBER,
};

/*
 * Struct: struct ZenitError
 *  All the errors that occur in the compilation are tracked by objects of this type
 * 
 * Members:
 *  <const char> *message: The error explanation
 *  <struct ZenitSourceLocation> location: Where in the source the error occurred tracked by a <struct ZenitSourceLocation> object
 *  <enum ZenitErrorType> type: The type of the error being one of the <enum ZenitErrorType> values
 * 
 */
struct ZenitError {
    const char *message;
    struct ZenitSourceLocation location;
    enum ZenitErrorType type;
};

/*
 * Struct: struct ZenitContext
 *  Keeps track of the information generated in the compilation
 *  process.
 * 
 * Members:
 *  <struct ZenitError> *errors: Array of <struct ZenitError> objects that occur in the compilation process
 *  <struct ZenitAst> *ast: Contains a reference to the AST generated by the parser
 *  <struct ZenitSourceInfo> *srcinfo: <struct ZenitSourceInfo> object to track files, lines and columns
 *  <struct ZenitProgram> *program: The object that contains the program being compiled
 */
struct ZenitContext {
    FlList errors;
    struct ZenitAst *ast;
    struct ZenitSourceInfo *srcinfo;
    struct ZenitProgram *program;
};

/*
 * Function: zenit_context_new
 *  Creates a new <struct ZenitContext> object that can be used to start the compilation process.
 *
 * Parameters:
 *  <enum ZenitSourceType> type: The origin or source from where to get the program's source code
 *  <const char> *input: Based on the *type* parameter this could be a filename or the program's source code
 *
 * Returns:
 *  <struct ZenitContext>: A context object ready to be used in the compilation process
 *
 * Notes:
 *  The object returned by this function internally allocates memory for its properties, so
 *  the user must free that memory with the <zenit_context_free> function
 */
struct ZenitContext zenit_context_new(enum ZenitSourceType type, const char *input);

/*
 * Function: zenit_context_free
 *  Releases the memory of an object allocated with the <zenit_context_new> function
 *
 * Parameters:
 *  <struct ZenitContext> *ctx: object to free
 *
 * Returns:
 *  void: This function does not return a value
 */
void zenit_context_free(struct ZenitContext* ctx);

/*
 * Function: zenit_context_error
 *  Adds a new <struct ZenitError> object to the <struct ZenitContext>'s *errors* property
 *
 * Parameters:
 *  <struct ZenitContext> *ctx: Context object
 *  <struct ZenitSourceLocation> location: Object that contains information of where in the source code the error happened
 *  <enum ZenitErrorType> type: The code that represents the type of the error
 *  <const char> *message: A string that accepts format specifiers containing information about the error
 *  *...*: Depending on the format string, the function may expect a sequence of additional arguments, each containing 
 *          a value to be used to replace a format specifier in the format string.
 *
 * Returns:
 *  void: This function does not return a value
 */
void zenit_context_error(struct ZenitContext *ctx, struct ZenitSourceLocation location, enum ZenitErrorType type, const char *message, ...);

/*
 * Function: zenit_context_print_errors
 *  Print all the errors registered in the context object to the standard error
 *
 * Parameters:
 *  <struct ZenitContext> *ctx - Context object
 *
 * Returns:
 *  void - This function does not return a value
 *
 */
void zenit_context_print_errors(struct ZenitContext *ctx);

#endif /* ZENIT_CONTEXT_H */
