#ifndef ZENIT_CONTEXT_H
#define ZENIT_CONTEXT_H

#include "ast/ast.h"
#include "symtable.h"
#include "source.h"
#include "program.h"
#include "types/context.h"

/*
 * Macro: zenit_context_error_count
 *  Returns the number of *errors* registered in the <ZenitContext> object
 *
 * Parameters:
 *  <ZenitContext> *ctxptr: A pointer to a <ZenitContext> object
 */
#define zenit_context_error_count(ctxptr) ((size_t)((ctxptr)->errors ? fl_list_length((ctxptr)->errors) : 0))


/*
 * Macro: zenit_context_has_errors
 *  Evaluates to *true* if the are *errors* registered in the <ZenitContext> object 
 *
 * Parameters:
 *  <ZenitContext> *ctxptr: A pointer to a <ZenitContext> object
 */
#define zenit_context_has_errors(ctxptr) ((ctxptr)->errors && fl_list_head((ctxptr)->errors) != NULL)

/*
 * Enum: ZenitErrorType 
 *  Represents every type of error that might occur in the
 *  compilation process
 *
 */
typedef enum ZenitErrorType {
    // Zenit specific errors
    ZENIT_ERROR_INTERNAL,

    // Mostly missing/unexpected tokens
    ZENIT_ERROR_SYNTAX,

    // Number cannot be represented by any integer type
    ZENIT_ERROR_LARGE_INTEGER,

    // Symbol couldn't be found
    ZENIT_ERROR_MISSING_SYMBOL,

    // Symbol already exists
    ZENIT_ERROR_DUPLICATED_SYMBOL,

    // Cannot infer the type of an expression
    ZENIT_ERROR_INFERENCE,

    // An operation involves types that are incompatible
    ZENIT_ERROR_TYPE_MISSMATCH,

    // Error taking a reference from an expression
    ZENIT_ERROR_INVALID_REFERENCE,

    // A member of a compound type does not exist
    ZENIT_ERROR_UNKNOWN_MEMBER,

    // A member of a compound type is not initialized on type instance creation
    ZENIT_ERROR_UNINITIALIZED_MEMBER,
} ZenitErrorType;

/*
 * Struct: ZenitError
 *  All the errors that occur in the compilation are tracked by objects of this type
 * 
 * Members:
 *  <const char> *message: The error explanation
 *  <ZenitSourceLocation> location: Where in the source the error occurred tracked by a <ZenitSourceLocation> object
 *  <ZenitErrorType> type: The type of the error being one of the <ZenitErrorType> values
 * 
 */
typedef struct ZenitError {
    const char *message;
    ZenitSourceLocation location;
    ZenitErrorType type;
} ZenitError;

/*
 * Struct: ZenitContext
 *  Keeps track of the information generated in the compilation
 *  process.
 * 
 * Members:
 *  <FlList> *errors: List of <ZenitError> objects that occur in the compilation process
 *  <ZenitAst> *ast: Contains a reference to the AST generated by the parser
 *  <ZenitSourceInfo> *srcinfo: <ZenitSourceInfo> object to track files, lines and columns
 *  <ZenitProgram> *program: The object that contains the program being compiled
 */
typedef struct ZenitContext {
    FlList *errors;
    ZenitAst *ast;
    ZenitSourceInfo *srcinfo;
    ZenitProgram *program;
    ZenitTypeContext *types;
} ZenitContext;

/*
 * Function: zenit_context_new
 *  Creates a new <ZenitContext> object that can be used to start the compilation process.
 *
 * Parameters:
 *  <ZenitSourceType> type: The origin or source from where to get the program's source code
 *  <const char> *input: Based on the *type* parameter this could be a filename or the program's source code
 *
 * Returns:
 *  <ZenitContext>: A context object ready to be used in the compilation process
 *
 * Notes:
 *  The object returned by this function internally allocates memory for its properties, so
 *  the user must free that memory with the <zenit_context_free> function
 */
ZenitContext zenit_context_new(ZenitSourceType type, const char *input);

/*
 * Function: zenit_context_free
 *  Releases the memory of an object allocated with the <zenit_context_new> function
 *
 * Parameters:
 *  <ZenitContext> *ctx: object to free
 *
 * Returns:
 *  void: This function does not return a value
 */
void zenit_context_free(ZenitContext* ctx);

/*
 * Function: zenit_context_error
 *  Adds a new <ZenitError> object to the <ZenitContext>'s *errors* property
 *
 * Parameters:
 *  <ZenitContext> *ctx: Context object
 *  <ZenitSourceLocation> location: Object that contains information of where in the source code the error happened
 *  <ZenitErrorType> type: The code that represents the type of the error
 *  <const char> *message: A string that accepts format specifiers containing information about the error
 *  *...*: Depending on the format string, the function may expect a sequence of additional arguments, each containing 
 *          a value to be used to replace a format specifier in the format string.
 *
 * Returns:
 *  void: This function does not return a value
 */
void zenit_context_error(ZenitContext *ctx, ZenitSourceLocation location, ZenitErrorType type, const char *message, ...);

/*
 * Function: zenit_context_print_errors
 *  Print all the errors registered in the context object to the standard error
 *
 * Parameters:
 *  <ZenitContext> *ctx - Context object
 *
 * Returns:
 *  void - This function does not return a value
 *
 */
void zenit_context_print_errors(ZenitContext *ctx);

#endif /* ZENIT_CONTEXT_H */
